name: Build on Multiple Platforms

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        compiler: [gcc, clang]

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      - name: Install GCC and Clang on Windows
        if: matrix.os == 'windows-latest' && matrix.compiler == 'gcc'
        run: |
          choco install mingw
          echo "C:\\tools\\mingw64\\bin" >> $GITHUB_PATH
        shell: powershell

      - name: Install GCC and Clang on Windows
        if: matrix.os == 'windows-latest' && matrix.compiler == 'clang'
        run: |
          choco install llvm
          echo "C:\\Program Files\\LLVM\\bin" >> $GITHUB_PATH
        shell: powershell

      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0

      - name: Build the project
        run: cmake --build build

      - name: Test the project
        run: ctest --test-dir build
