name: Build on Multiple Platforms

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        compiler: [gcc, clang]

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0

      - name: Configure the project
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=$CXX_COMPILER
        env:
          CXX_COMPILER: ${{ matrix.compiler }}

      - name: Build the project
        run: cmake --build build

      - name: Test the project
        run: ctest --test-dir build
